export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCESS: 'LOGIN_SUCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCESS: 'LOGOUT_SUCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}

export const userContants = {
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCESS: 'USER_REGISTER_SUCESS',
    USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE'
}